//
// Constants
//

export const ACHIEVEMENT_SUPPORT =
{
	NONE: "NONE",
	INGAME: "INGAME",
	LAUNCHER: "LAUNCHER",
};

export const COMPLETION_STATUS =
{
	TODO: "TODO",
	IN_PROGRESS: "IN_PROGRESS",
	COMPLETE: "COMPLETE",
	ONE_HUNDRED_PERCENT: "ONE_HUNDRED_PERCENT",
};

export const CONTROLLER_SUPPORT =
{
	NONE: "NONE",
	SUPPORTED: "SUPPORTED",
	REQUIRED: "REQUIRED",
};

export const MOD_SUPPORT =
{
	NONE: "NONE",
	SUPPORTED: "SUPPORTED",
	REQUIRED: "REQUIRED",
};

export const PROGRESSION_TYPE =
{
	NONE: "NONE",
	NON_CAMPAIGN: "NON_CAMPAIGN",
	CAMPAIGN: "CAMPAIGN",
};

export const VIRTUAL_REALITY_SUPPORT =
{
	NONE: "NONE",
	SUPPORTED: "SUPPORTED",
	REQUIRED: "REQUIRED",
};